import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const PUBLIC_DIR = join(process.cwd(), 'public');

function generate() {
  mkdirSync(PUBLIC_DIR, { recursive: true });

  // --- llms.txt (English) ---
  const llmsLines = [
    '# Aperture',
    '',
    '> A markdown-first wiki and life system for agent-native work.',
    '> It turns raw notes, links, transcripts, and daily logs into a browsable knowledge graph with source provenance, semantic trails, and agent APIs.',
    '',
    '## Links',
    '',
    '- [Repository](https://github.com/ZepPellN/Aperture)',
    '- [README](https://github.com/ZepPellN/Aperture#readme)',
    '- [Author](https://x.com/plutozeppln)',
    '',
    '## What It Is',
    '',
    'Aperture is a Next.js viewer that reads plain markdown files from your filesystem and compiles them into a structured knowledge system.',
    'It is not a note-taking app. It is a lens: you keep writing markdown as you always have, and Aperture renders it as something you and your agents can explore.',
    '',
    '## Core Capabilities',
    '',
    '### Wiki System',
    '- Article pages at `/wiki/<slug>` with rendered markdown, wikilink resolution, source provenance tracking, evolution timeline, backlinks, and semantic neighbor trails.',
    '- Homepage with keyword + semantic search, category browsing, recently-updated timeline, and stats.',
    '- Source provenance: every article tracks where its ideas came from (inline links, absorb logs, frontmatter, manual contributions) with contribution levels.',
    '',
    '### Graph Exploration (4 views)',
    '- **Network Graph** — Sigma.js WebGL force-directed graph. Focus mode, cluster highlighting, camera animation.',
    '- **Topo Map** — Canvas-based topographic density visualization using D3 contours. Category-colored glows, hover tooltips.',
    '- **Semantic Map** — Same topo visual language, laid out by UMAP semantic coordinates instead of force-directed placement.',
    '- **Nest Graph** — React Three Fiber 3D organic cluster. Seed-shaped nodes, animated growing edges, orbit controls.',
    '',
    '### Semantic Infrastructure',
    '- UMAP dimensionality reduction from text embeddings.',
    '- Cosine-similarity neighbor computation for semantic trails and random walk.',
    '- DBSCAN clustering for knowledge islands at `/clusters`.',
    '',
    '### Life Dashboard',
    '- `/life` compiles daily journals, weekly intents, habit trackers, and goals into a unified dashboard.',
    '- Weekly stats, intent cards (STOP/START/FORGIVE/SELF-CARE), next actions, mood timeline, habit heatmap, task velocity chart, life areas, and weekly reviews.',
    '',
    '### Agent APIs',
    '- `/api/wiki/<slug>` — JSON API returning slug, title, category, markdown, HTML, sources, backlinks, semantic neighbors, reading time, word count.',
    '- `/llms.txt` and `/llms-full.txt` — agent-readable system descriptions.',
    '- Bundled Claude Code skills in `.agents/skills/` for wiki maintenance.',
    '',
    '## Core Routes',
    '',
    '- `/` — Homepage: search, categories, recently updated, stats',
    '- `/wiki/<slug>` — Article page with provenance, evolution, backlinks, mini graph',
    '- `/graph` — Full-screen graph explorer with 4 view modes',
    '- `/clusters` — Semantic cluster browser',
    '- `/walk` — Random walk through semantic neighbors',
    '- `/life` — Personal life dashboard',
    '- `/api/wiki/<slug>` — JSON API for article data',
    '',
    '## Data Format',
    '',
    '- Source files: plain markdown with YAML frontmatter.',
    '- Wikilink syntax: `[[slug|label]]`.',
    '- Life data: custom markdown formats in `witness/` and `life-wiki/` directories.',
    '- No database. No proprietary format. File-over-app.',
    '',
    '## Agent Onboarding',
    '',
    'Tell your agent to read `AGENT_SETUP.md` for full setup: vault scaffolding, skill installation, content ingestion, and viewer launch.',
    '',
  ];
  writeFileSync(join(PUBLIC_DIR, 'llms.txt'), llmsLines.join('\n'), 'utf-8');

  // --- llms-zh.txt (Chinese) ---
  const llmsZhLines = [
    '# Aperture',
    '',
    '> 一个面向 AI Agent 的 Markdown-first 个人 Wiki 系统。',
    '> 将原始笔记、链接、摘录和日常日志转换为可浏览的知识图谱，保留来源出处、语义关联、演化历史，并为 AI 提供结构化 API。',
    '',
    '## 链接',
    '',
    '- [开源仓库](https://github.com/ZepPellN/Aperture)',
    '- [项目主页](https://github.com/ZepPellN/Aperture#readme)',
    '- [作者](https://x.com/plutozeppln)',
    '',
    '## 这是什么',
    '',
    'Aperture 是一个 Next.js 查看器，从文件系统读取纯 Markdown 文件，并将其编译为结构化知识系统。',
    '它不是笔记应用，而是一个透镜：你像往常一样写 Markdown，Aperture 将其渲染为你和你的 Agent 可以探索的东西。',
    '',
    '## 核心能力',
    '',
    '### Wiki 系统',
    '- `/wiki/<slug>` 文章页面：渲染后的 Markdown、wikilink 解析、来源追踪、演化时间线、反向链接、语义邻居路径。',
    '- 首页：关键词搜索 + 语义扩展搜索、分类浏览、最近更新时间线、统计栏。',
    '- 来源出处：每篇文章追踪其思想来源（内联链接、吸收日志、frontmatter、手动贡献），并标注贡献度等级。',
    '',
    '### 图谱探索（4 种视图）',
    '- **Network Graph** — Sigma.js WebGL 力导向图。聚焦模式、集群高亮、相机动画。',
    '- **Topo Map** — Canvas 等高线密度地形图，D3 contour。分类色晕、悬浮提示。',
    '- **Semantic Map** — 同等视觉语言，但使用 UMAP 语义坐标而非力导向布局。',
    '- **Nest Graph** — React Three Fiber 3D 有机集群。种子形状节点、生长动画边、轨道控制。',
    '',
    '### 语义基础设施',
    '- 基于文本嵌入的 UMAP 降维。',
    '- 余弦相似度邻居计算，用于语义路径和随机漫步。',
    '- DBSCAN 聚类，在 `/clusters` 发现知识岛屿。',
    '',
    '### 生活仪表盘',
    '- `/life` 将每日日记、每周意图、习惯追踪和目标列表编译为统一仪表盘。',
    '- 每周统计、意图卡片（STOP/START/FORGIVE/SELF-CARE）、下一步行动、心情时间线、习惯热力图、任务速度图、生活领域、周回顾。',
    '',
    '### Agent API',
    '- `/api/wiki/<slug>` — JSON API，返回 slug、标题、分类、Markdown、HTML、来源、反向链接、语义邻居、阅读时间、字数。',
    '- `/llms.txt` 和 `/llms-full.txt` — 供 Agent 阅读的系统描述。',
    '- `.agents/skills/` 中捆绑的 Claude Code skills，用于 Wiki 维护。',
    '',
    '## 核心路由',
    '',
    '- `/` — 首页：搜索、分类、最近更新、统计',
    '- `/wiki/<slug>` — 文章页（来源、演化、反向链接、迷你图）',
    '- `/graph` — 全屏图谱浏览器（4 种视图）',
    '- `/clusters` — 语义聚类浏览器',
    '- `/walk` — 语义邻居随机漫步',
    '- `/life` — 个人生活仪表盘',
    '- `/api/wiki/<slug>` — 文章数据 JSON API',
    '',
    '## 数据格式',
    '',
    '- 源文件：带 YAML frontmatter 的纯 Markdown。',
    '- Wikilink 语法：`[[slug|label]]`。',
    '- 生活数据：`witness/` 和 `life-wiki/` 目录中的自定义 Markdown 格式。',
    '- 无数据库。无专有格式。文件优先。',
    '',
    '## Agent 接入',
    '',
    '让 Agent 读取 `AGENT_SETUP.md` 即可完成全套部署：仓库脚手架、技能安装、内容摄取、启动查看器。',
    '',
  ];
  writeFileSync(join(PUBLIC_DIR, 'llms-zh.txt'), llmsZhLines.join('\n'), 'utf-8');

  // --- llms-full.txt (English detailed) ---
  const fullLines = [
    '# Aperture — Full System Description',
    '',
    '> A markdown-first wiki and life system for agent-native work.',
    '> It turns raw notes, links, transcripts, and daily logs into a browsable knowledge graph with source provenance, semantic trails, and agent APIs.',
    '',
    '## Links',
    '',
    '- [Repository](https://github.com/ZepPellN/Aperture)',
    '- [README](https://github.com/ZepPellN/Aperture#readme)',
    '- [Author](https://x.com/plutozeppln)',
    '',
    '## Philosophy',
    '',
    'Three constraints govern every decision:',
    '',
    '1. **Markdown-first** — Source files are plain markdown with YAML frontmatter. No lock-in, no proprietary format.',
    '2. **File-over-app** — Your data lives in your filesystem, not a database. The app is just a viewer.',
    '3. **Agent-native** — Every feature is designed so that AI agents can read, write, and maintain it programmatically.',
    '',
    '## Architecture',
    '',
    'Aperture is a Next.js 16 application. It reads markdown files from `WIKI_ROOT` at build time, compiles them to HTML, computes graph structures, and generates static pages.',
    'Semantic features (UMAP, neighbors, clusters) are precomputed by `scripts/build-semantic.ts` and stored as JSON in `lib/`.',
    'Life data is parsed from `witness/` and `life-wiki/` directories by `lib/life-loader.ts`.',
    '',
    '## Wiki Engine',
    '',
    '### Article Rendering',
    '- Markdown parsed with `gray-matter` for frontmatter.',
    '- HTML compiled with `unified` + `remark-gfm` + `remark-rehype` + `rehype-slug` + `rehype-stringify`.',
    '- Wikilinks (`[[slug|label]]`) are resolved to internal links; broken links are marked.',
    '- Reading time and word count are computed from plain text.',
    '',
    '### Source Provenance',
    'Every article aggregates sources from four origins:',
    '1. **Body links** — URLs and wikilinks found in the article body.',
    '2. **Absorb logs** — Records from `_absorb_log.json` tracking when raw sources were ingested.',
    '3. **Frontmatter** — `sources` array in YAML frontmatter.',
    '4. **Contributions** — Manual source contributions from `_source_contributions.json`.',
    '',
    'Each source receives a contribution level: high, medium, low, or unknown.',
    '',
    '### Evolution Tracking',
    'Article histories are stored in `_evolution.json`. Events include: created, absorbed, merged, split, renamed, refined, linked.',
    'The evolution timeline is displayed on every article page.',
    '',
    '### Backlinks',
    'Backlinks are computed at build time by scanning all articles for wikilink references.',
    'The `_backlinks.json` file caches this data.',
    '',
    '### Search',
    '- **Keyword mode** — substring matching on title and content.',
    '- **Semantic mode** — expands results to include semantic neighbors of keyword matches.',
    '- Keyboard navigation (arrow keys, Enter) supported.',
    '',
    '## Graph System',
    '',
    '### Data Model',
    '- Nodes = articles. Size proportional to link count. Color = category.',
    '- Edges = wikilinks. Undirected.',
    '- Local graph = 1-degree neighborhood of a focus node.',
    '',
    '### Network Graph (Sigma.js)',
    '- WebGL rendering with SVG fallback.',
    '- Layout: ForceAtlas2 (force-directed).',
    '- Interactions: hover highlights node + neighbors; click opens article; focus mode isolates neighborhood; cluster focus isolates category.',
    '- Camera: animated transitions on focus change.',
    '- Theme-aware palettes for light/dark mode.',
    '',
    '### Topo Map (Canvas + D3)',
    '- Density field computed from node positions.',
    '- D3 contours drawn as filled bands.',
    '- Category-colored glows around nodes.',
    '- Edge rendering with opacity by distance.',
    '- Category centroid labels.',
    '- Hover tooltips with link stats.',
    '- Two layout modes: force-directed and UMAP semantic.',
    '',
    '### Nest Graph (React Three Fiber)',
    '- 3D scene with perspective camera.',
    '- Categories arranged in circular layout with simplex noise perturbation.',
    '- Nodes rendered as organic "seed" shapes (line-segment bursts).',
    '- Edges as animated growing arcs.',
    '- Cluster hover highlighting.',
    '- Camera smooth-focus on click.',
    '- Orbit controls: left-drag pan, right-drag rotate, scroll zoom.',
    '- Selection card with "Read article" button.',
    '',
    '## Semantic Infrastructure',
    '',
    '### Build Pipeline (`scripts/build-semantic.ts`)',
    '1. Reads qmd SQLite vector database.',
    '2. Mean-pools chunk embeddings per article.',
    '3. Runs UMAP dimensionality reduction to 2D.',
    '4. Computes cosine-similarity top-5 neighbors per article.',
    '5. Runs DBSCAN clustering on UMAP coordinates.',
    '',
    '### Outputs',
    '- `lib/semantic-layout.json` — UMAP 2D coordinates per slug.',
    '- `lib/semantic-neighbors.json` — Top-5 neighbors per slug.',
    '- `lib/semantic-clusters.json` — DBSCAN clusters with centroids and members.',
    '',
    '## Life Dashboard',
    '',
    '### Data Sources',
    '- `witness/diary/` — Daily journal entries with mood, energy, habits, tasks.',
    '- `witness/weekly/` — Weekly intent files (STOP/START/FORGIVE/SELF-CARE).',
    '- `life-wiki/goals.md` — Goal lists by domain.',
    '- `life-wiki/life-areas.md` — Life area definitions.',
    '- `life-wiki/weekly-reviews/` — Generated weekly review files.',
    '- `life-wiki/tasks/` — Generated weekly task files.',
    '',
    '### Components',
    '- Stats bar: week number, pending/completed/ideas counts.',
    '- Intent cards: four colored cards for weekly intentions.',
    '- Next actions: grid of extracted action items.',
    '- Mood timeline: bar chart (dominant emotion + energy level per day).',
    '- Habit heatmap: exercise, meals, sleep, supplements.',
    '- Task velocity: stacked bar chart (pending vs done per week).',
    '- Recent diaries: expandable entries.',
    '- Life areas: collapsible sections with goal counts.',
    '- 2026 goals: domain-grouped with expandable plans.',
    '- Weekly reviews: collapsible historical summaries.',
    '',
    '## Agent APIs',
    '',
    '### `/api/wiki/<slug>`',
    'Returns JSON:',
    '- `slug`, `title`, `category`',
    '- `content` — raw markdown',
    '- `html` — compiled HTML',
    '- `sources` — array of source objects (path, label, level, origin)',
    '- `backlinks` — array of slugs that link to this article',
    '- `semanticNeighbors` — array of neighbor objects (slug, title, score)',
    '- `readingTime` — minutes',
    '- `wordCount` — integer',
    '',
    '### LLM Text Files',
    '- `/llms.txt` — Compact system description (English).',
    '- `/llms-zh.txt` — Compact system description (Chinese).',
    '- `/llms-full.txt` — Detailed system description (English, this file).',
    '- `/llms-full-zh.txt` — Detailed system description (Chinese).',
    '',
    '### Bundled Skills',
    'Claude Code skills in `.agents/skills/` include:',
    '- `wiki-absorb` — Ingest raw sources into wiki articles.',
    '- `wiki-health` — Audit wiki quality (broken links, thin pages, orphans).',
    '- `wiki-query` — Query the wiki with natural language.',
    '- `wiki-triage` — Compare raw sources against existing articles.',
    '- `life-insight` — Generate weekly insight reports.',
    '- `life-intent` — Set weekly intentions.',
    '- `life-reflect` — Daily reflection prompts.',
    '',
    '## Automation Scripts',
    '',
    '| Script | Command | Purpose |',
    '|---|---|---|',
    '| `build-semantic.ts` | `npm run build:semantic` | Rebuild embeddings, UMAP, neighbors, clusters |',
    '| `generate-llms-txt.ts` | `npm run generate:llms-txt` | Regenerate agent-readable text files |',
    '| `export-wiki.ts` | `npm run export:wiki` | Export wiki as timestamped ZIP |',
    '| `graph-proposal.ts` | `npm run graph:proposal` | Generate research proposals for topics/clusters |',
    '| `insight-report.ts` | `npm run insight` | Generate themed reports from natural language queries |',
    '| `task-extract.ts` | `npm run tasks` | Extract tasks from journals and intents |',
    '| `weekly-review.ts` | `npm run weekly-review` | Generate weekly review Markdown from daily journals |',
    '| `wiki-entities.ts` | `npm run wiki:entities` | Analyze entity mentions and suggest links |',
    '| `wiki-health.ts` | `npm run wiki:health` | Audit wiki health and quality |',
    '',
    '## Setup',
    '',
    'For agents: read `AGENT_SETUP.md`.',
    '',
    'For manual setup:',
    '```bash',
    'git clone https://github.com/ZepPellN/Aperture.git',
    'cd Aperture',
    'npm install',
    'cp .env.example .env.local',
    '# Set WIKI_ROOT=/absolute/path/to/your/vault',
    'npm run dev',
    '```',
    '',
    'Environment variables:',
    '- `WIKI_ROOT` — Absolute path to the vault directory (required)',
    '- `QMD_INDEX` — Path to qmd SQLite index (optional, for semantic features)',
    '',
    '## License',
    '',
    'MIT',
    '',
  ];
  writeFileSync(join(PUBLIC_DIR, 'llms-full.txt'), fullLines.join('\n'), 'utf-8');

  // --- llms-full-zh.txt (Chinese detailed) ---
  const fullZhLines = [
    '# Aperture — 完整系统描述',
    '',
    '> 一个面向 AI Agent 的 Markdown-first 个人 Wiki 系统。',
    '> 将原始笔记、链接、摘录和日常日志转换为可浏览的知识图谱，保留来源出处、语义关联、演化历史，并为 AI 提供结构化 API。',
    '',
    '## 链接',
    '',
    '- [开源仓库](https://github.com/ZepPellN/Aperture)',
    '- [项目主页](https://github.com/ZepPellN/Aperture#readme)',
    '- [作者](https://x.com/plutozeppln)',
    '',
    '## 设计哲学',
    '',
    '三条约束指导每一个设计决策：',
    '',
    '1. **Markdown-first** — 源文件是带 YAML frontmatter 的纯 Markdown。无锁定，无专有格式。',
    '2. **File-over-app** — 数据存于文件系统，而非数据库。应用只是查看器。',
    '3. **Agent-native** — 每个功能都设计为 AI Agent 可以以编程方式读取、写入和维护。',
    '',
    '## 架构',
    '',
    'Aperture 是一个 Next.js 16 应用。它在构建时从 `WIKI_ROOT` 读取 Markdown 文件，编译为 HTML，计算图结构，并生成静态页面。',
    '语义功能（UMAP、邻居、聚类）由 `scripts/build-semantic.ts` 预先计算，以 JSON 形式存储于 `lib/`。',
    '生活数据由 `lib/life-loader.ts` 从 `witness/` 和 `life-wiki/` 目录解析。',
    '',
    '## Wiki 引擎',
    '',
    '### 文章渲染',
    '- Markdown 通过 `gray-matter` 解析 frontmatter。',
    '- HTML 通过 `unified` + `remark-gfm` + `remark-rehype` + `rehype-slug` + `rehype-stringify` 编译。',
    '- Wikilink（`[[slug|label]]`）解析为内部链接；断链标记。',
    '- 阅读时间和字数从纯文本计算。',
    '',
    '### 来源出处',
    '每篇文章从四个来源聚合来源信息：',
    '1. **正文链接** — 文章正文中找到的 URL 和 wikilink。',
    '2. **吸收日志** — `_absorb_log.json` 中记录的原始来源摄取记录。',
    '3. **Frontmatter** — YAML frontmatter 中的 `sources` 数组。',
    '4. **贡献记录** — `_source_contributions.json` 中的手动来源贡献。',
    '',
    '每个来源标注贡献度等级：高、中、低、未知。',
    '',
    '### 演化追踪',
    '文章历史存储于 `_evolution.json`。事件包括：创建、吸收、合并、拆分、重命名、精炼、链接。',
    '演化时间线显示在每篇文章页面底部。',
    '',
    '### 反向链接',
    '反向链接在构建时通过扫描所有文章的 wikilink 引用计算。',
    '`_backlinks.json` 缓存此数据。',
    '',
    '### 搜索',
    '- **关键词模式** — 标题和正文的子串匹配。',
    '- **语义模式** — 将结果扩展到关键词匹配的语义邻居。',
    '- 支持键盘导航（方向键、回车）。',
    '',
    '## 图谱系统',
    '',
    '### 数据模型',
    '- 节点 = 文章。大小与链接数成正比。颜色 = 分类。',
    '- 边 = wikilink。无向。',
    '- 局部图 = 焦点节点的 1 度邻居。',
    '',
    '### Network Graph（Sigma.js）',
    '- WebGL 渲染，SVG 降级。',
    '- 布局：ForceAtlas2（力导向）。',
    '- 交互：悬浮高亮节点+邻居；点击打开文章；聚焦模式隔离邻居；集群聚焦隔离分类。',
    '- 相机：聚焦变化时的动画过渡。',
    '- 主题感知调色板，支持亮色/暗色模式。',
    '',
    '### Topo Map（Canvas + D3）',
    '- 从节点位置计算密度场。',
    '- D3 等高线作为填充色带绘制。',
    '- 节点周围分类色晕。',
    '- 按距离透明度的边渲染。',
    '- 分类质心标签。',
    '- 悬浮提示显示链接统计。',
    '- 两种布局模式：力导向和 UMAP 语义。',
    '',
    '### Nest Graph（React Three Fiber）',
    '- 透视相机的 3D 场景。',
    '- 分类以圆形布局排列，simplex noise 扰动。',
    '- 节点渲染为有机"种子"形状（线段爆发）。',
    '- 边为动画生长弧线。',
    '- 集群悬浮高亮。',
    '- 点击时相机平滑聚焦。',
    '- 轨道控制：左键拖动平移，右键拖动旋转，滚轮缩放。',
    '- 选择卡片带"阅读文章"按钮。',
    '',
    '## 语义基础设施',
    '',
    '### 构建流水线（`scripts/build-semantic.ts`）',
    '1. 读取 qmd SQLite 向量数据库。',
    '2. 每篇文章对 chunk 嵌入做均值池化。',
    '3. 运行 UMAP 降维至 2D。',
    '4. 计算每篇文章的余弦相似度 top-5 邻居。',
    '5. 在 UMAP 坐标上运行 DBSCAN 聚类。',
    '',
    '### 输出',
    '- `lib/semantic-layout.json` — 每篇文章的 UMAP 2D 坐标。',
    '- `lib/semantic-neighbors.json` — 每篇文章的 top-5 邻居。',
    '- `lib/semantic-clusters.json` — DBSCAN 聚类，含质心和成员。',
    '',
    '## 生活仪表盘',
    '',
    '### 数据源',
    '- `witness/diary/` — 含心情、能量、习惯、任务的每日日记。',
    '- `witness/weekly/` — 每周意图文件（STOP/START/FORGIVE/SELF-CARE）。',
    '- `life-wiki/goals.md` — 按领域分类的目标列表。',
    '- `life-wiki/life-areas.md` — 生活领域定义。',
    '- `life-wiki/weekly-reviews/` — 生成的周回顾文件。',
    '- `life-wiki/tasks/` — 生成的周任务文件。',
    '',
    '### 组件',
    '- 统计栏：周数、待办/已完成/想法计数。',
    '- 意图卡片：四张彩色卡片对应每周意图。',
    '- 下一步行动：提取的行动项网格。',
    '- 心情时间线：柱状图（每天主导情绪 + 能量水平）。',
    '- 习惯热力图：运动、饮食、睡眠、补剂。',
    '- 任务速度：堆叠柱状图（每周待办 vs 已完成）。',
    '- 最近日记：可展开条目。',
    '- 生活领域：可折叠区域，显示目标数。',
    '- 2026 目标：按领域分组，可展开计划。',
    '- 周回顾：可折叠历史摘要。',
    '',
    '## Agent API',
    '',
    '### `/api/wiki/<slug>`',
    '返回 JSON：',
    '- `slug`、`title`、`category`',
    '- `content` — 原始 Markdown',
    '- `html` — 编译后的 HTML',
    '- `sources` — 来源对象数组（path、label、level、origin）',
    '- `backlinks` — 链接到本文的文章 slug 数组',
    '- `semanticNeighbors` — 邻居对象数组（slug、title、score）',
    '- `readingTime` — 分钟',
    '- `wordCount` — 整数',
    '',
    '### LLM 文本文件',
    '- `/llms.txt` — 简洁系统描述（英文）。',
    '- `/llms-zh.txt` — 简洁系统描述（中文）。',
    '- `/llms-full.txt` — 详细系统描述（英文）。',
    '- `/llms-full-zh.txt` — 详细系统描述（中文，本文件）。',
    '',
    '### 捆绑 Skills',
    '`.agents/skills/` 中的 Claude Code skills 包括：',
    '- `wiki-absorb` — 将原始来源摄取为 Wiki 文章。',
    '- `wiki-health` — 审计 Wiki 质量（断链、薄弱页面、孤儿）。',
    '- `wiki-query` — 自然语言查询 Wiki。',
    '- `wiki-triage` — 对比原始来源与现有文章。',
    '- `life-insight` — 生成每周洞察报告。',
    '- `life-intent` — 设定每周意图。',
    '- `life-reflect` — 每日反思提示。',
    '',
    '## 自动化脚本',
    '',
    '| 脚本 | 命令 | 用途 |',
    '|---|---|---|',
    '| `build-semantic.ts` | `npm run build:semantic` | 重建嵌入、UMAP、邻居、聚类 |',
    '| `generate-llms-txt.ts` | `npm run generate:llms-txt` | 重新生成 Agent 可读文本文件 |',
    '| `export-wiki.ts` | `npm run export:wiki` | 导出 Wiki 为带时间戳的 ZIP |',
    '| `graph-proposal.ts` | `npm run graph:proposal` | 为主题/聚类生成研究提案 |',
    '| `insight-report.ts` | `npm run insight` | 从自然语言查询生成主题报告 |',
    '| `task-extract.ts` | `npm run tasks` | 从日记和意图中提取任务 |',
    '| `weekly-review.ts` | `npm run weekly-review` | 从每日日记生成周回顾 Markdown |',
    '| `wiki-entities.ts` | `npm run wiki:entities` | 分析实体提及并建议链接 |',
    '| `wiki-health.ts` | `npm run wiki:health` | 审计 Wiki 健康和质量 |',
    '',
    '## 部署',
    '',
    'Agent 部署：阅读 `AGENT_SETUP.md`。',
    '',
    '手动部署：',
    '```bash',
    'git clone https://github.com/ZepPellN/Aperture.git',
    'cd Aperture',
    'npm install',
    'cp .env.example .env.local',
    '# 设置 WIKI_ROOT=/absolute/path/to/your/vault',
    'npm run dev',
    '```',
    '',
    '环境变量：',
    '- `WIKI_ROOT` — 仓库目录的绝对路径（必需）',
    '- `QMD_INDEX` — qmd SQLite 索引路径（可选，用于语义功能）',
    '',
    '## 许可证',
    '',
    'MIT',
    '',
  ];
  writeFileSync(join(PUBLIC_DIR, 'llms-full-zh.txt'), fullZhLines.join('\n'), 'utf-8');

  console.log('[llms.txt] Generated 4 files in public/: llms.txt, llms-zh.txt, llms-full.txt, llms-full-zh.txt');
}

generate();
